# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:55
from __future__ import unicode_literals


from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_created', models.DateTimeField(verbose_name='Activity Created On')),
                ('activity_detail', models.CharField(max_length=1000, verbose_name='Activity')),
                ('activity_star', models.BooleanField(verbose_name='Mark this as milestone.')),
                ('activity_goal_map', models.CharField(max_length=500, verbose_name='Goal Nick Name')),
                ('activity_user', models.CharField(max_length=500, verbose_name='Activity User')),
                ('activity_weightage', models.IntegerField(blank=True, null=True, verbose_name='Activity Weightage')),
            ],
            options={
                'db_table': 'lt_activities',
                'verbose_name_plural': 'Daily Activities',
            },
        ),
        migrations.CreateModel(
            name='ShortTermGoals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_slug', models.CharField(max_length=500, unique=True, verbose_name='Goal Name (Slug Form)')),
                ('goal_desc', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Short Description')),
                ('goal_status', models.BooleanField(default=False, verbose_name='Goal Achieved?')),
                ('goal_updated', models.DateTimeField(blank=True, default=timezone.now(), null=True, verbose_name='Last Updated On')),
                ('goal_target', models.DateTimeField(blank=True, null=True, verbose_name='Expected Completion Date')),
                ('goal_category', models.CharField(max_length=500, verbose_name='Goal Category')),
                ('goal_notes', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Notes or Remarks')),
            ],
            options={
                'db_table': 'lt_goals',
                'verbose_name': 'Short Term Goal',
            },
        ),
    ]
