# Generated by Django 2.2.6 on 2020-01-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logtoday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalTasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_subject', models.CharField(max_length=400, verbose_name='Task Subject')),
                ('task_details', models.CharField(max_length=1000, verbose_name='Task Details')),
                ('task_created_on', models.DateTimeField(verbose_name='Activity Created On')),
                ('task_target_date', models.DateTimeField(verbose_name='Task Target Date')),
                ('task_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Task Completion Date')),
                ('task_goal_map', models.CharField(max_length=500, verbose_name='Map with Goal')),
                ('task_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Goal Tasks',
                'db_table': 'lt_tasks',
                'ordering': ['task_target_date'],
            },
        ),
    ]
