# Generated by Django 2.2.6 on 2020-01-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtoday', '0002_goaltasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermgoals',
            name='goal_slug',
            field=models.SlugField(max_length=500, unique=True, verbose_name='Goal Name (Slug Form)'),
        ),
    ]
