# Generated by Django 3.0.8 on 2020-07-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logtoday', '0003_auto_20200121_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltasks',
            name='task_target_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Task Target Date'),
        ),
    ]
